### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by jeromecc** [github/choosealicense.com#478] opened 2017-02-04 16:58 UTC
Hi!
I belong to a French open source collective called [LibreHealthCare](https://librehealthcare.org).
We are considering starting a translation of choosealicence.com
Would it be possible to make this project "I18N" friendly, allowing the use of translation files?
If other people are thinking about translating this site, please let me know.
Thanks.

**Comment by mlinksva** [comment] 2017-02-04 20:50
Hi @jeromecc, closing this as a duplicate of #68, let's continue the discussion there.

We haven't settled on an approach to making the site i18n friendly. I'd love to but could use help figuring it out.

Note that there's an existing but outdated French translation (in a fork, not using any i18n facility) as noted in https://github.com/github/choosealicense.com/issues/68#issuecomment-210596788 that may be worth updating while we figure out a longer term plan.

**Closed as completed by mlinksva** 2017-02-04 20:50 UTC
