### ISSUE TITLE
Bug: Appendix page renders badly scrolling down

### ISSUE THREAD

**Issue by DeflateAwning** [github/choosealicense.com#1239] opened 2024-08-17 23:46 UTC
See the following screenshot:

![image](https://github.com/user-attachments/assets/4e9c926b-27d7-4e4c-8968-5e489f862ed1)

Page: https://choosealicense.com/appendix/

Fix: Add an opaque background fill to the header row of that table.

**Comment by matthijsgroen** [comment] 2024-08-20 07:43
Duplicate of #1110

**Closed as completed** 2024-08-30 19:11 UTC
