### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by nasirkhan** [github/choosealicense.com#548] opened 2017-10-31 04:44 UTC
Is there any option to localize the https://choosealicense.com platform? if so, how can i contribute?

**Comment by mlinksva** [comment] 2017-10-31 05:05
The only option right now is to fork and translate in place on the fork as mentioned at https://github.com/github/choosealicense.com/issues/68#issuecomment-328930491 ... assuming we eventually have a better i18n mechanism it's possible that l10n would merit a separately maintained fork anyway.

For now I'm closing this as a duplicate of #68. Please subscribe to that for and make updates there. Thanks!

**Closed as completed by mlinksva** 2017-10-31 05:05 UTC
