### ISSUE TITLE
Need Attribution-NonCommercial-ShareAlike 4.0 International

### ISSUE THREAD

**Issue by FredQSWang** [github/choosealicense.com#1020] opened 2022-08-21 13:38 UTC
_Attribution-NonCommercial-ShareAlike 4.0 International (**CC BY-NC-SA 4.0**)_

I'm very sorry. I need [_Attribution-NonCommercial-ShareAlike 4.0 International_](https://creativecommons.org/licenses/by-nc-sa/4.0/) on my Github.
I hope you can add it to your website. I think you can do it.
Many thanks.

**Comment by nschonni** [comment] 2022-08-21 14:18
Probably a duplicate of https://github.com/github/choosealicense.com/issues/481, but if you want a license added https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by mlinksva** [comment] 2022-08-21 15:24
No need to apologize. Out of scope for this project per the link Nick posted, but you can use whatever license you want, as you've done https://github.com/TangelScratchStudio/TangelStudio-OfficialWeb/blob/57524dc5734990203c2f08bebde8b42551d3c2cc/LICENSE (though note you've specified a different CC license in that project's README; I'd guess you'd want those to match).

**Closed as completed by mlinksva** 2022-08-21 15:24 UTC
