### ISSUE TITLE
Mix of software and content?

### ISSUE THREAD

**Issue by afeld** [github/choosealicense.com#97] opened 2013-10-05 18:08 UTC
An example:

I teach a JS class and have all my materials [in a repo](https://github.com/afeld/advanced_js) - both written materials, assignments, etc., and functional code that makes the slide deck itself work.  I want to "properly" open source the whole thing.

What is the best way to handle these cases?  Creative Commons [discourages](http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) use of its licenses for software, but the language of something like the MIT license sound very code-specific.  Do I need to include one license code, one for non-code?  Where is that line drawn?  Are there any licenses that can cover all of it?  While I'm sure it's impossible to give a general, definitive answer, some guidance in the FAQ might be helpful.

/cc @hoolio

**Comment by haacked** [comment] 2013-10-28 23:30
> Do I need to include one license code, one for non-code?

That's pretty much what I would do. It could be as simple as having an MIT license in the root with a brief blurb that it applies to the source code.

For the content, you'd typically have a footer that mentions it's creative commons. See the footer on haacked.com for an example.

**Comment by haacked** [comment] 2013-10-28 23:30
> some guidance in the FAQ might be helpful.

Want to submit a PR?

**Comment by afeld** [comment] 2013-10-29 01:38
The outstanding question is: can one license be used for both?  e.g. with code samples, which do those count as?  For MIT license, for example, do you _need_ to specify a different license for the content?

**Comment by haacked** [comment] 2013-10-29 02:10
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files

Hmm, seems like MIT is primarily concerned with software. I suppose you could consider your training materials to be part of the software. It seems like you're stretching it though. MIT wasn't intended for content, it was intended for software.

> do you need to specify a different license for the content?

You don't _need_ to do anything. As with most things, the real question is what a court would decide. So what is the scenario here that would require a court decision?

I can think of one scenario.

My guess is that the risk isn't to you at all, but to people using your content. The risk is you (the copyright holder) might come along later and say they don't have rights to copy your content, just the code. I don't know what a court would decide in that case. Perhaps they might rule in your favor because existing conventions for content is to apply a copyright notice on the content itself or use a content-friendly license like CC.

So if you wanted to use MIT only, perhaps add a note to the top that says it applies to source code and content. That would mitigate the risk to people using your content. If you later claimed the license didn't apply to the content, they could point to this note you made as evidence of your true intentions.

Personally, I would use a content-friendly license for content according to existing conventions that people understand and would make everyone comfortable and your intentions explicit. But I don't see any real reason why you couldn't call this entire work "Software" and use just an MIT license.

I do think it'd be interesting to hear from @talniv, @benbalter, or @hoolio about their thoughts on my IANAL amateur analysis. :smile:

**Comment by benbalter** [comment] 2013-10-30 14:30
Closing, but feel free to reopen if I'm wrong. Don't know that setting the precedent that if you have a question about license implementation, you should open an issue on choosealicense.com... can get into some sticky legal water, among other things like not being even remotely scalable. _This is not an IP legal clinic. Most of us are not lawyers. This is not legal advice. Issues should be limited to site improvements, especially when other avenues are available._

> Creative Commons discourages use of its licenses for software

Except CC0. You can use CC0 for both if you don't care about retaining copyright.

>  Do I need to include one license code, one for non-code?

Very common to license code under MIT and content under a CC flavor. See e.g., [this project](https://github.com/github/choosealicense.com#license).

It's all about communicating intention. Just make it clear in the Readme. A file called `LICENSE` in the root of the repo is a convention, but A) it's not being machine read, so the convention really doesn't matter all that much, and B) it's not necessarily legally binding. You could put the MIT license in a file called `LICENSE`, but then in the read me say "I just like to include the text of the MIT license in my projects, but this project is licensed under the GPL license. You can find the full text [here](#)." If litigated, most would agree that the author's intent is GPL.

Just be clear in the readme with what rights you want to grant to others for what content.

For more background _see_ [this thread from project open data](https://github.com/project-open-data/project-open-data.github.io/pull/135)

**Closed as completed by benbalter** 2013-10-30 14:30 UTC
Labels: question

**Comment by afeld** [comment] 2013-12-29 06:48
> Don't know that setting the precedent that if you have a question about license implementation, you should open an issue on choosealicense.com

Totally understand.  I was using my case as an example for the larger question, which I think is broadly applicable.
