### ISSUE TITLE
BSD (3-Clause) License license should populate all placeholders

### ISSUE THREAD

**Issue by izuzak** [github/choosealicense.com#109] opened 2013-10-25 16:49 UTC
Creating a repository with the BSD (3-Clause) License doesn't define values for all placeholders in the license. 

Specifically, the `{organization}` placeholder is not replaced with any value, and this has to be done manually after creating the repository:

https://github.com/github/choosealicense.com/blob/gh-pages/licenses/bsd-3-clause.txt#L38

A better approach might be to replace `{organization}` with `{fullname}`.

cc @Haacked @benbalter

**Comment by bhuga** [comment] 2013-10-25 17:30
These interpolate correctly on .com again. If we want to update the licenses it's another thing.

**Comment by haacked** [comment] 2013-10-25 18:06
@bhuga huh? I didn't understand your comment. Could you clarify?

**Comment by bhuga** [comment] 2013-10-25 18:08
We had a bug for a while were almost nothing would get interpolated. Creating a new repo with a BSD-3 now adds a fullname: https://github.com/bhuga/testlicense/blob/master/LICENSE#L1

**Comment by haacked** [comment] 2013-10-25 18:11
@bhuga ah! Thanks for fixing that. But this bug is specifically about the `{organization}` field in the BSD-3.

> Neither the name of the {organization} nor the names of it

You can see it a few lines into your test license. The suggestion is to change that to `fullname` instead of `organization`. OR, perhaps we change the code on the .com side to fill it in. Which I'm starting to think is preferred because I'd rather not mess with the license texts.

**Comment by bhuga** [comment] 2013-10-25 18:16
Ah, so we just missed that one in https://github.com/github/choosealicense.com/pull/55! That's my bad; sorry, I misunderstood.

Should be as simple as updating it to `[fullname]` and re-importing to .com.

**Comment by haacked** [comment] 2013-10-25 18:25
So what I'm wondering is, can we make it work by keeping it [organization] here? Or is that just dumb? I'm just a tiny bit wary of changing the text on this site to something it's not in the original.

**Comment by bhuga** [comment] 2013-10-25 18:32
We don't replace `[organization]`, just `[fullname]` of the repository owner (because which organization would it be? What if there is none?). So it would read a bit weird for personal ownership; I suppose that whole line would have to be removed, and, well...yuck?

Not sure we can solve this one cleanly and easily.

**Comment by haacked** [comment] 2013-10-25 18:46
Well I guess 999 times out of 1000, the person applying this license is probably also the "organization". So maybe we just also replace "[organization]" with the "[fullname]". And the user can correct it.

Or, we could do nothing and let people manually correct it. @benbalter and I figured we should do it automatically because if it's not correct in that 1 time in a 1000, then they probably have an organization they're working with who have a strong incentive and legal resources to correct it.

**Comment by ghost** [comment] 2013-11-06 02:37
+1 for using the [fullname] placeholder, for the reason above.

I'm also thinking that if there is another organization with incentive to correct it, they likely have a trademark on the name, which probably means they have other legal tools to enforce proper use of the name.

**Comment by talniv** [comment] 2013-11-06 18:21
Probably I'm misunderstanding, but, @Haacked, can't it be `organization` when there is one, and `fullname` when there isn't? 
(clearly, I'm :+1: for populating)

**Comment by haacked** [comment] 2013-11-06 23:56
@talniv what do you mean by `organization` in this context?

**Comment by bhuga** [comment] 2013-11-07 01:23
I think the problem is that the wording is just awkward for `[fullname]`, which expands either to the name or the organization:

> - Neither the name of the {organization} nor the names of its
>   contributors may be used to endorse or promote products derived from
>   this software without specific prior written permission.

It assumes an organization. Have we changed the license meaningfully if we change it to the following?:

> Neither [fullname] nor the name of any contributor may be used to endorse or promote products derived from this software without specific prior written permission

**Comment by ghost** [comment] 2013-11-07 02:49
Ah, good point. For the record, small changes exist in BSD licenses in use. The organization name changes, and sometimes slightly more words. Example results of an analysis on Firefox OS included software:
http://projects.opensource.org/pipermail/license-discuss/2012-November/000686.html

Example choice on this issue, from another license project:
https://licensedb.org/id/BSD-3-Clause.html

On Github, 
https://github.com/search?q=%22nor+the+names+of+its+contributors%22&type=Code&ref=searchresults
https://github.com/search?q=%22nor+the+name+of+any+contributor%22&type=Code&ref=searchresults
Some are indeed author and its contributors.

IMHO a variant won't be vetted by any authority of sorts. Unfortunately I'd still be +1 on the standard text.
(and, who needs grammar when we have lawyers? :sparkles:)

**Comment by bsdlp** [comment] 2014-03-22 04:58
[lice](https://github.com/licenses/lice/blob/master/lice/template-bsd3.txt) is apparently using `[project]` in place of `{organization}`. Either way, it would be great if this patch were to be merged or a decision be made.

**Comment by benbalter** [comment] 2014-06-17 16:45
PR over in https://github.com/github/choosealicense.com/pull/208.

**Closed as completed** 2014-06-17 21:26 UTC
