### ISSUE TITLE
What about internationalization?

### ISSUE THREAD

**Issue by whilein** [github/choosealicense.com#808] opened 2021-03-04 17:03 UTC
Could you add the ability to change the language, please?

**Comment by nschonni** [comment] 2021-03-04 17:38
Duplicate of https://github.com/github/choosealicense.com/issues/68, but the title might be better if it was renamed there

**Comment by mlinksva** [comment] 2021-03-12 19:52
Closing as duplicate of #68 which does remain open because I intend to get to it eventually.

**Closed as completed by mlinksva** 2021-03-12 19:52 UTC

**Comment by nschonni** [comment] 2021-03-12 20:23
@mlinksva it might be good to update the title up #68 to something like "Internationalization / i18n / multilingual site" just as a catch all of things that people would likely search for if they try looking before opening an issue
