### ISSUE TITLE
Provide API to obtain license data

### ISSUE THREAD

**Issue by derks** [github/choosealicense.com#84] opened 2013-09-04 17:36 UTC
It would be nice if you could provide a simple API to return the license data via JSON, or even just a standard URL structure that would allow us to obtain just the raw license.  That is actually the reason why I created the following (before this project existed):
- https://github.com/datafolklabs/license

There is another project I maintain called BOSS which builds projects from templates, and supports pulling in the license content dynamically from the above repo.  I'd like to change that to use 'ChooseALicense' however it doesn't appear there is any way to just get the raw license text.

**Comment by benbalter** [comment] 2013-09-04 17:53
@derks Believe this is a dupe of #40, which was resolved in #47. Let me know if you have any trouble consuming the API.

**Closed as completed by benbalter** 2013-09-04 17:53 UTC

**Comment by derks** [comment] 2013-09-04 18:36
I see that Issue #47 references the following:
- http://choosealicense.com/javascripts/annotations.js

That URL doesn't provide licenses.  Can you please provide an example of how to pull license data, specifically for an individual license?  I suppose you could turn this issue into "Document How To Access License API".

Thanks.

**Comment by benbalter** [comment] 2013-09-04 18:46
#47 exposes all the licenses as http://choosealicense.com/licenses.json. Because of limitations in Jekyll, it'd be hard to expose the licenses individually a `.json` file, for example. Would love help better documenting the API.

**Comment by derks** [comment] 2013-09-04 18:51
That URL is getting warmer, the only thing missing is the actual license txt.

**Comment by benbalter** [comment] 2013-09-04 22:08
That's unfortunately, the limitation of Jekyll I was alluding to. Having the same content in multiple formats is a bit tricky. You can however, use the [GitHub content API](http://developer.github.com/v3/repos/contents/) to grab the contents of a given file. It may be helpful for us to expose `file_path` within the index as `page.path`.

**Comment by pketh** [comment] 2017-10-23 19:07
https://choosealicense.com/licenses.json 404s, is there a newer way to get license data via JSON?

**Comment by benbalter** [comment] 2017-10-23 19:18
https://developer.github.com/v3/licenses/ is an API of the license data from choosealicense.com

**Comment by tomeks666** [comment] 2018-06-21 20:27
https://api.github.com/licenses lists only 12 licenses while there is clearly more. E.g ms-pl is not listed, but using https://api.github.com/licenses/ms-pl I get its record. Is this something by design or a bug?

**Comment by wking** [comment] 2018-06-21 20:52
> https://api.github.com/licenses lists only 12 licenses while there is clearly more. E.g ms-pl is not listed, but using https://api.github.com/licenses/ms-pl I get its record. Is this something by design or a bug?

Seems like a bug to me.  I checked for the `Link` header [GitHub uses for pagination][1], and didn't see it:

```console
$ curl -Is https://api.github.com/licenses | grep -i link
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
```

so I think something is broken in the backend, or there are undocumented query parameters for filtering `/licenses` or something...

[1]: https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by mlinksva** [comment] 2018-06-22 20:46
Pretty clearly https://api.github.com/licenses is returning the 12 licenses cataloged here without `hidden: false`.

I'll pass on the feedback above to those maintaining the relevant API and documentation.
