### ISSUE TITLE
Replacing MIT and BSD recommendations with Blue Oak

### ISSUE THREAD

**Issue by jab** [github/choosealicense.com#816] opened 2021-03-28 16:32 UTC
I just saw https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html, which explains why MIT and BSD licenses should no longer be used for new work, and recommends using the [Blue Oak license](https://blueoakcouncil.org/license/1.0.0) instead. I immediately checked choosealicense.com, and when I didn't see mention of this there, I checked this issue tracker, and finally am creating a new issue since it doesn't look like this has been discussed here yet. I'm not a licensing expert myself, but am just interested in following whether GitHub and choosealicense.com are interested in considering this further. Thanks!

CC @kemitchell (please feel free to take over here if interested:)

**Comment by kemitchell** [comment] 2021-03-28 17:40
Thanks for mentioning, @jan. I'll watch this issue.

**Comment by nschonni** [comment] 2021-03-28 18:08
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
Looks like it meets 1, but likely none of the others

**Comment by mlinksva** [comment] 2021-04-05 02:28
Happy to catalog BlueOak-1.0.0 here when it meets criteria linked to above.

For convenience a [crude search](https://github.com/search?q=filename%3ALICENSE+%22Blue+Oak+Model+License%22) currently gets 506 hits.

**Comment by Aspie96** [comment] 2021-06-13 13:40
(**I am not a lawyer and this is not legal advice**)

I strongly disagree with this.

It is better to suggest well known and widely used licenses.

The Blue Oak license is rarely used (and when it is used, it's mostly as a template for other licenses).

Also, consider the idea that Mitchell might be a bit biased about this. The opinion of other lawyers too is needed.

I am not a lawyer, but as evidence of the fact that MIT is hard to read, Mitchell claims that it is hard to read and cites his own guide to the MIT license: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html

However, I'd argue that such guide doesn't help his point at all, because pretty much all that he wrote in such guide is obvious from reading the MIT license.

Then he claims:
> In other words, if you use someone’s software under MIT or BSD and share a copy without including their copyright notices and license terms, they can sue you for infringement, since the open source license no longer applies to you.

This, however, is (I'd argue) is exactly as intended. The MIT license has one easy to follow condition.

He also cites the huge amount of variants of MIT and BSD. But this is only a problem if one qualifies their license only with "BSD" (which should never be done). In pretty much every case I've seen of projects claiming to be under the MIT license, it has been the same version of the license and all of the widely known licenses which are sometimes referred to as "MIT license" are essentially equivalent.

In addition, what license is used is clear because as long as the license is included in the project. And even if it is not (but it should) the SPDX identifier, if provided, identifies the specific license being used.

As for the contributors part, the assumption that contributions are under the same license as the project is widespread in the OS community. It is justified by community norm and as an industry standard. In practice, it's clear from the fact that provided commits represent a version of the repository including the same license and the contribution is provided for inclusion. See: https://google.github.io/opencasebook/authorship/
> The standard mechanism for contributing to an open source project is the submission of a pull request, which entails re-copying the entire repository along with the contributed changes, together with all of the project’s existing documentation, when submitting the contribution. Through this mechanism, a contributor is formally publishing the contribution under the license of the project.

Also, the MIT and BSD licenses have been evaluated and considered free by Debian and the FSF as well. Only licenses which are clearly FLOSS according to everyone should be suggested. The Blue Oak license has only been evaluated by OSI.

**Comment by Aspie96** [comment] 2021-06-13 14:03
Note: I am not against merely listing the license when it does meet the necessary criteria.
But I believe the *suggested* licenses on the homepage should be the most common ones and ones which have been evaluated and accepted by the FLOSS community as a whole. The most influential entities for evaluation are the FSF (steward of the free software definition), OSI (steward of the open source definition) and Debian (widely influential, adopts both terms, is usually more restrictive than both OSI and FSF, is considered fully free by the FSF, and was the foundation for the open source definition).

**Comment by balupton** [comment] 2021-07-19 07:26
> But I believe the _suggested_ licenses on the homepage should be the most common ones and ones which have been evaluated and accepted by the FLOSS community as a whole.

How do you expect other licenses to make headway, if the monopolised licenses are the only ones granted listing?

However, if you are stating that all should be listed, however only some should be suggested - then I'm not sure who this suggestion is intended serve, at the end, the license suggested to me, should be the one that meets my checkboxes as a maintainer — if two licenses are equivalent however, then popularity is a good metric, but when comparing apples to oranges, I'm not going to select the one that more popular but doesn't fit my requirements.

Increasing the diversity of licenses is a good thing, more matches for more diverse requirements, less square pegs in round holes.

**Comment by sskras** [comment] 2021-09-22 11:56
> https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
> Looks like it meets 1, but likely none of the others

Quoting 2:
> > The license must be listed on one of the following approved lists of licenses:
> > - List of OSI approved licenses
> > - GNU's list of free licenses (note: the license must be listed in one of the three "free" categories)

Just wrote to <licensing@fsf.org> an application to review the `BlueOak-1.0.0`.

**Comment by sskras** [comment] 2021-10-06 10:21
I received the `[gnu.org #1760802]` ticket there.
GNU volunteer <[ineiev](mailto:ineiev@gnu.org)> updated state of the review on 30 Sep 2021:

> Thank you for checking in on this.  License review is a resource
> intensive process, often requiring the involvement of legal counsel.
> As such, we have a backlog of requests for review.  This license is
> already on the queue, but I unfortunately cannot give an estimate as
> to when that review will be completed.  Thanks again for checking in,
> and I hope this helps.

**Comment by mlinksva** [comment] 2022-06-04 19:23
Since I just made a [similar point](https://github.com/github/choosealicense.com/issues/997#issuecomment-1146671601) on another issue let me agree with @Aspie96's point:

> It is better to suggest well known and widely used licenses.

Like I wrote a year ago:

> Happy to catalog BlueOak-1.0.0 here when it meets criteria linked to above.

Feel free to submit a PR.

Closing this issue as changing "recommendation" is a long way off.

**Closed as completed by mlinksva** 2022-06-04 19:23 UTC

**Comment by sskras** [comment] 2024-01-29 20:46
FWIW, the BlueOak model license just got OSI approval: https://github.com/spdx/license-list-XML/issues/2352

> Happy to catalog BlueOak-1.0.0 here when it meets criteria linked to above.

Now onto the requirement number 3:

![image](https://github.com/github/choosealicense.com/assets/7887758/f351f673-169d-489d-a331-7616dbf21e05)

> For convenience a [crude search](https://github.com/search?q=filename%3ALICENSE+%22Blue+Oak+Model+License%22) currently gets 506 hits.

The search syntax has changed, and now this query returns 0 results sadly.

**Comment by jab** [comment] 2024-01-29 21:21
[This search](https://github.com/search?q=%22Blue+Oak+Model+License%22+path%3A**%2FLICENSE&type=code&ref=advsearch) currently returns 35 results, fwiw

**Comment by Aspie96** [comment] 2024-01-29 22:11
Although it was pretty clear that the license was permissive, it's interesting to see that it got OSI approval, so thanks @sskras for reporting this.

**Comment by balupton** [comment] 2024-01-30 00:57
638 results supporting license extensions: https://github.com/search?q=%22Blue+Oak+Model+License%22+path%3A**%2FLICENSE*&type=code&ref=advsearch

**Comment by sskras** [comment] 2024-01-30 10:59
That contains quite a bit of false positives.

I used Regexp syntax to avoid descending into directories: `"Blue Oak Model License" path:/^LICENSE.*$/`
It gives [333](https://github.com/search?q=%22Blue+Oak+Model+License%22++path%3A%2F%5ELICENSE.*%24%2F&type=code) matches.

But that also contains some false positives.

So I tried refining it: `https://blueoakcouncil.org/license/1.0.0 path:/^(LICENSE|COPY).*$/ `
But this says to find [305 files](https://github.com/search?q=https%3A%2F%2Fblueoakcouncil.org%2Flicense%2F1.0.0+path%3A%2F%5E%28LICENSE%7CCOPY%29.*%24%2F+&type=code&ref=advsearch) at the moment, which is clearly wrong.

Wrong query, wrong results or probably both at the same time.

That's because a year ago I already had **collected 616 repos** by using the old version of GitHub search:
https://github.com/sskras/license-test/blob/master/repo-list-using-blueoak.md#the-main-list:~:text=2023%2D02%2D07%20Updated%2C%20now%20616%20(%2B%2024)%20items.
(Please scroll two lines above that anchor)

So I tried a generic query with a bunch of exceptions: `https://blueoakcouncil.org/license/1.0.0 path:/^[^\/]+$/ NOT "osiApproved" NOT "Project ID" NOT ".json" NOT spdx-license-list NOT Apache-2.0 NOT "Parity Public License" NOT "Round Robin Software License" NOT "Apache License"`
This returns me [662 files](https://github.com/search?q=https%3A%2F%2Fblueoakcouncil.org%2Flicense%2F1.0.0+path%3A%2F%5E%5B%5E%5C%2F%5D%2B%24%2F+NOT+%22osiApproved%22+NOT+%22Project+ID%22+NOT+%22.json%22+NOT+spdx-license-list+NOT+Apache-2.0+NOT+%22Parity+Public+License%22+NOT+%22Round+Robin+Software+License%22+NOT+%22Apache+License%22&type=code&ref=advsearch) at the moment.

But even this result cannot be trusted. I simplified the query down to: `"Blue Oak Model License" path:/^COPYING.*$/`
And [it says `3 files`](https://github.com/search?q=%22Blue+Oak+Model+License%22++path%3A%2F%5ECOPYING.*%24%2F&type=code) while presenting me list of **9 files** out of which  4 come from the forked repos, which leaves us with **5 unique files**.

So the number is not to be trusted much.
